### ISSUE TITLE
Can't understand this repo

### ISSUE THREAD

**Issue by Dr-Wade** [trashcluster/SDcard-DB-copier#2]
I can't understand the structure of this repo:
* What is the difference between all the .ps1 files
* Windows Defender prevents me from opening the .exe file: what's going on here?

Please advice.

**Comment by trashcluster** [comment]
Hi @Dr-Wade, the differents .ps1 files are here because i forgot what's the difference between all of them.  
If windows defender prevents you from opening the .exe just deactivate windows defender duh!

Have a nice week !

**Comment by Dr-Wade** [comment]
Thank you for your explanations! I just must compliment you with the choice of your username, it's pretty accurate
